name: "LaunchFlow Deploy Action"
description: "GitHub action to deploy your code to LaunchFlow"
author: "LaunchFlow Inc."
inputs:
  project_id:
    description: "The LaunchFlow project to deploy to. Should be of the format `project_XXXXXX`"
    required: true
  from_environment_name:
    description: "The LaunchFlow environment to promote from (from -> to)."
    required: true
  to_environment_name:
    description: "The LaunchFlow environment to promote to (from -> to)."
    required: true
  deployment_key:
    description: "The LaunchFlow deployment key of the environment you are promoting to use for authentication."
    required: true
  working_dir:
    description: "The working directory to run the deploy from. Defaults to the root of the repository."
    required: false
    default: "."
  launchflow_cli_version:
    description: "The version of the LaunchFlow CLI to use. Defaults to the latest version."
    required: false
    default: ""
branding:
  icon: "cloud"
  color: "purple"
runs:
  using: composite
  steps:
    - run: |
        python3 $GITHUB_ACTION_PATH/action/main.py
      env:
        INPUT_FROM_ENVIRONMENT: ${{ inputs.from_environment_name }}
        INPUT_TO_ENVIRONMENT: ${{ inputs.to_environment_name }}
        INPUT_PROJECT_ID: ${{ inputs.project_id }}
        INPUT_DKEY: ${{ inputs.deployment_key }}
        INPUT_CLI_VERSION: ${{ inputs.launchflow_cli_version }}
      shell: bash
